# Generated by Django 5.2.1 on 2025-06-06 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_address', models.CharField(max_length=255, verbose_name='Адрес размещения')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('office', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('computer_name', models.CharField(max_length=100, unique=True, verbose_name='Имя компьютера')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP-адрес')),
                ('domain', models.CharField(max_length=100, verbose_name='Домен')),
                ('has_kaspersky', models.BooleanField(default=False, verbose_name='Установлен Касперский')),
                ('operating_system', models.CharField(choices=[('win10', 'Windows 10'), ('win11', 'Windows 11'), ('linux', 'Linux'), ('macos', 'MacOS'), ('other', 'Другая')], default='win10', max_length=20, verbose_name='Операционная система')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'ordering': ['computer_name'],
            },
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_description', models.TextField(verbose_name='Описание изменения')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='computers.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'Изменение',
                'verbose_name_plural': 'Изменения',
                'ordering': ['-change_date'],
            },
        ),
    ]
