# Generated by Django 5.2.1 on 2025-06-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_alter_changes_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='computer_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='changes',
            name='computer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя компьютера'),
        ),
    ]
