# Generated by Django 5.2.1 on 2025-06-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_changes_computer_ip_changes_computer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
