# Generated by Django 5.2.1 on 2025-06-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_computer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(max_length=100, verbose_name='Имя компьютера'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ip_address',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='IP-адрес'),
        ),
    ]
