# Generated by Django 5.2.1 on 2025-06-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0005_alter_computer_computer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(max_length=60, verbose_name='Операционная система'),
        ),
    ]
