# Generated by Django 5.2.1 on 2025-06-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0006_alter_computer_operating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='pc_owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пользователь компьютера'),
        ),
        migrations.AddField(
            model_name='computer',
            name='pc_owner_position_at_work',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность пользователя'),
        ),
    ]
